ALTER TABLE "ComboProduct" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ComboProduct" DROP COLUMN IF EXISTS "link";
ALTER TABLE "ComboProduct" DROP COLUMN IF EXISTS "sortOrder";
